CREATE DATABASE pernscheduling;

-- Create table for events
CREATE TABLE Events(
    EVENT_ID SERIAL PRIMARY KEY,
    EVENT_NAME VARCHAR(255),
    EVENT_MINHOUR TIME,
    EVENT_MAXHOUR TIME,
    EVENT_DURATION TIME,
    EVENT_MINNUMPLAYERS INTEGER,
    EVENT_MAXNUMPLAYERS INTEGER
);

-- Create table for participants
CREATE TABLE Participants(
    PARTICIPANT_ID SERIAL PRIMARY KEY,
    PARTICIPANT_FNAME VARCHAR(255),
    PARTICIPANT_LNAME VARCHAR(255),
    PARTICIPANT_PWORD VARCHAR(255)
);

-- Create week days table
CREATE TABLE Week_Days(
    WEEK_DAY VARCHAR(255) PRIMARY KEY
);

-- Create event days table
CREATE TABLE Event_Days(
    EVENT_DAY_ID SERIAL PRIMARY KEY,
    EVENT_ID SERIAL,
    WEEK_DAY VARCHAR(255),
    FOREIGN KEY (EVENT_ID) REFERENCES Events(EVENT_ID),
    FOREIGN KEY (WEEK_DAY) REFERENCES Week_Days(WEEK_DAY)
);

-- Create participation table
CREATE TABLE Participation(
    PARTICIPATION_ID SERIAL PRIMARY KEY,
    EVENT_ID SERIAL,
    PARTICIPANT_ID SERIAL,
    FOREIGN KEY (EVENT_ID) REFERENCES Events(EVENT_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES Participants(PARTICIPANT_ID)
);

-- Create participation days table
CREATE TABLE Participation_Days(
    PARTICIPATION_DAY_ID SERIAL PRIMARY KEY,
    WEEK_DAY VARCHAR(255),
    PARTICIPATION_ID SERIAL,
    FOREIGN KEY (WEEK_DAY) REFERENCES Week_Days(WEEK_DAY),
    FOREIGN KEY (PARTICIPATION_ID) REFERENCES Participation(PARTICIPATION_ID)
);

-- Create day slots table
CREATE TABLE Participation_Day_Slots(
    PARTICIPATION_DAY_SLOT_ID SERIAL PRIMARY KEY,
    PARTICIPATION_DAY_ID SERIAL,
    PARTICIPATION_DAY_SLOT_START TIME,
    PARTICIPATION_DAY_SLOT_END TIME,
    FOREIGN KEY (PARTICIPATION_DAY_ID) REFERENCES Participation_Days(PARTICIPATION_DAY_ID)
);